PIN_ROOT ?= ../../pin-external-4.3-99850-gce5652921-gcc-linux
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config

include $(CONFIG_ROOT)/makefile.config

TOOL_ROOTS := cacheline_trace

include $(TOOLS_ROOT)/Config/makefile.default.rules
