// Exact sparse GF(2) map search for 32 fixed 64-bit patterns.
//
// The search is intentionally data-dependent: a row is represented by its
// 64-bit input mask, while its 32-bit signature is used for fast partition
// checks.  Candidates are generated by increasing tap weight, deduplicated by
// signature, and combined with an exact group-splitting DFS.
//
// Build:
//   c++ -O3 -std=c++17 tools/search_linear_mphf.cpp -o /tmp/search_linear_mphf
// Run:
//   /tmp/search_linear_mphf results/mphf-32/codebook1.txt

#include <algorithm>
#include <array>
#include <chrono>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

namespace {

constexpr unsigned kKeys = 32;
constexpr unsigned kRows = 5;
using Key = std::uint64_t;
using Signature = std::uint32_t;

unsigned popcount64(Key x) {
  return static_cast<unsigned>(__builtin_popcountll(x));
}

unsigned popcount32(Signature x) {
  return static_cast<unsigned>(__builtin_popcount(x));
}

struct Candidate {
  unsigned weight;
  Signature signature;
  Key mask;
};

struct Best {
  std::array<Key, kRows> rows{};
  std::array<unsigned, kKeys> ids{};
  unsigned taps = std::numeric_limits<unsigned>::max();
};

struct Stage {
  unsigned cap = 0;
  std::size_t candidates = 0;
  std::uint64_t nodes = 0;
  bool complete = false;
  std::vector<unsigned> improvements;
};

enum class StopReason { None, Time, CandidateLimit };

struct Options {
  std::string path;
  double seconds = 60.0;
  unsigned max_cap = 5;
  std::size_t max_candidates = 250000;
};

std::string usage() {
  return "usage: search_linear_mphf CODEBOOK.txt [--seconds N] "
         "[--max-cap N] [--max-candidates N]";
}

std::uint64_t parse_uint(const std::string& text, const char* option) {
  std::size_t used = 0;
  const auto value = std::stoull(text, &used, 10);
  if (used != text.size()) throw std::runtime_error(std::string("bad ") + option);
  return value;
}

Options parse_options(int argc, char** argv) {
  if (argc < 2) throw std::runtime_error(usage());
  Options options;
  options.path = argv[1];
  for (int i = 2; i < argc; ++i) {
    const std::string arg = argv[i];
    if (arg == "--seconds" && i + 1 < argc) {
      options.seconds = std::stod(argv[++i]);
      if (!(options.seconds >= 0.0) || !std::isfinite(options.seconds))
        throw std::runtime_error("--seconds must be finite and nonnegative");
    } else if (arg == "--max-cap" && i + 1 < argc) {
      options.max_cap = static_cast<unsigned>(parse_uint(argv[++i], "--max-cap"));
      if (options.max_cap == 0 || options.max_cap > 64)
        throw std::runtime_error("--max-cap must be in 1..64");
    } else if (arg == "--max-candidates" && i + 1 < argc) {
      options.max_candidates = static_cast<std::size_t>(
          parse_uint(argv[++i], "--max-candidates"));
      if (options.max_candidates == 0)
        throw std::runtime_error("--max-candidates must be positive");
    } else {
      throw std::runtime_error("unknown option or missing value: " + arg);
    }
  }
  return options;
}

std::array<Key, kKeys> read_keys(const std::string& path) {
  std::ifstream input(path);
  if (!input) throw std::runtime_error("cannot open codebook: " + path);
  std::array<Key, kKeys> keys{};
  unsigned count = 0;
  std::string line;
  while (std::getline(input, line)) {
    std::string hex;
    for (const unsigned char c : line) {
      if (std::isxdigit(c)) {
        hex.push_back(static_cast<char>(c));
      } else if (std::isspace(c) || c == '|') {
        continue;
      } else {
        throw std::runtime_error(
            "each nonempty line must be | 16 hexadecimal digits |");
      }
    }
    if (hex.empty()) continue;
    if (hex.size() != 16 || count == kKeys)
      throw std::runtime_error("expected exactly 32 lines of 16 hex digits");
    Key value = 0;
    for (const unsigned char c : hex) {
      value <<= 4;
      value |= c <= '9' ? c - '0' : (std::tolower(c) - 'a' + 10);
    }
    keys[count++] = value;
  }
  if (count != kKeys) throw std::runtime_error("expected exactly 32 keys");
  for (unsigned i = 0; i < kKeys; ++i)
    for (unsigned j = i + 1; j < kKeys; ++j)
      if (keys[i] == keys[j]) throw std::runtime_error("duplicate key in codebook");
  return keys;
}

class Searcher {
 public:
  Searcher(const std::array<Key, kKeys>& keys, const Options& options)
      : keys_(keys), options_(options), deadline_(Clock::now()) {
    for (unsigned bit = 0; bit < 64; ++bit) {
      Signature column = 0;
      for (unsigned i = 0; i < kKeys; ++i)
        column |= static_cast<Signature>(((keys_[i] >> bit) & 1ULL) << i);
      columns_[bit] = column;
    }
  }

  std::string run() {
    start_ = Clock::now();
    deadline_ = start_ + std::chrono::duration_cast<Clock::duration>(
                                      std::chrono::duration<double>(options_.seconds));
    for (unsigned cap = 1; cap <= options_.max_cap; ++cap) {
      if (stop_ != StopReason::None) break;
      const auto stage_begin = Clock::now();
      enumerate_weight(cap, 0, cap, 0, 0);
      if (stop_ != StopReason::None) break;
      generated_cap_ = cap;
      rebuild_pool();
      const auto old_nodes = nodes_;
      const auto old_improvements = improvements_.size();
      const bool complete = search_stage();
      Stage stage;
      stage.cap = cap;
      stage.candidates = pool_.size();
      stage.nodes = nodes_ - old_nodes;
      stage.complete = complete;
      for (std::size_t i = old_improvements; i < improvements_.size(); ++i)
        stage.improvements.push_back(improvements_[i]);
      stages_.push_back(stage);
      std::cerr << "cap=" << cap << " candidates=" << pool_.size()
                << " nodes=" << stage.nodes
                << " complete=" << (complete ? "true" : "false")
                << " best=" << (best_ ? std::to_string(best_->taps) : "none")
                << " elapsed_ms="
                << std::chrono::duration<double, std::milli>(Clock::now() - stage_begin).count()
                << '\n';
      if (complete) proved_cap_ = cap;
      if (stop_ != StopReason::None) break;
      // Five taps is the absolute lower bound for five nonzero output rows.
      if (best_ && best_->taps == kRows) {
        status_ = "optimal";
        break;
      }
    }
    if (status_.empty()) {
      if (stop_ == StopReason::Time) status_ = "time_limit";
      else if (stop_ == StopReason::CandidateLimit) status_ = "candidate_limit";
      else if (best_) status_ = "optimal_in_pool";
      else status_ = "no_linear_map_in_pool";
    }
    return to_json();
  }

 private:
  using Clock = std::chrono::steady_clock;

  const std::array<Key, kKeys>& keys_;
  const Options& options_;
  std::array<Signature, 64> columns_{};
  std::unordered_map<Signature, Candidate> by_signature_;
  std::vector<Candidate> pool_;
  std::array<Key, kRows> chosen_{};
  std::optional<Best> best_;
  std::vector<unsigned> improvements_;
  std::vector<Stage> stages_;
  Clock::time_point start_;
  Clock::time_point deadline_;
  std::uint64_t enumerated_ = 0;
  std::uint64_t nodes_ = 0;
  unsigned generated_cap_ = 0;
  unsigned proved_cap_ = 0;
  StopReason stop_ = StopReason::None;
  std::string status_;

  void check_deadline() {
    if ((enumerated_ & 0x3ff) == 0 && Clock::now() >= deadline_)
      stop_ = StopReason::Time;
  }

  void enumerate_weight(unsigned target, unsigned start, unsigned left,
                        Key mask, Signature signature) {
    if (stop_ != StopReason::None) return;
    check_deadline();
    if (stop_ != StopReason::None) return;
    if (left == 0) {
      ++enumerated_;
      if (popcount32(signature) == 16) {
        const auto found = by_signature_.find(signature);
        if (found == by_signature_.end()) {
          if (by_signature_.size() >= options_.max_candidates) {
            stop_ = StopReason::CandidateLimit;
            return;
          }
          by_signature_.emplace(signature, Candidate{target, signature, mask});
        }
      }
      return;
    }
    for (unsigned bit = start; bit <= 64 - left; ++bit) {
      enumerate_weight(target, bit + 1, left - 1, mask | (Key{1} << bit),
                       signature ^ columns_[bit]);
      if (stop_ != StopReason::None) return;
    }
  }

  void rebuild_pool() {
    pool_.clear();
    pool_.reserve(by_signature_.size());
    for (const auto& entry : by_signature_) pool_.push_back(entry.second);
    std::sort(pool_.begin(), pool_.end(), [](const Candidate& a, const Candidate& b) {
      if (a.weight != b.weight) return a.weight < b.weight;
      if (a.signature != b.signature) return a.signature < b.signature;
      return a.mask < b.mask;
    });
    generated_cap_ = std::max(generated_cap_, pool_.empty() ? 0U : pool_.back().weight);
  }

  bool improves_bound(unsigned cost, unsigned remaining, const std::vector<int>& pool,
                      std::size_t begin) const {
    if (!best_) return false;
    if (pool.size() - begin < remaining) return true;
    unsigned lower = cost;
    for (unsigned i = 0; i < remaining; ++i) lower += pool_[pool[begin + i]].weight;
    return lower >= best_->taps;
  }

  bool splits(const std::vector<std::uint32_t>& groups, Signature signature,
              std::vector<std::uint32_t>* halves) const {
    if (halves) {
      halves->clear();
      halves->reserve(groups.size() * 2);
    }
    for (const auto group : groups) {
      const auto ones = group & signature;
      const auto zeros = group ^ ones;
      if (popcount32(ones) * 2 != popcount32(group)) return false;
      if (halves) {
        halves->push_back(ones);
        halves->push_back(zeros);
      }
    }
    return true;
  }

  bool search_stage() {
    if (Clock::now() >= deadline_) {
      stop_ = StopReason::Time;
      return false;
    }
    const std::vector<int> all = indices(0, pool_.size());
    const std::vector<std::uint32_t> groups{0xffffffffU};
    dfs(all, groups, 0, 0);
    return stop_ == StopReason::None;
  }

  static std::vector<int> indices(std::size_t begin, std::size_t end) {
    std::vector<int> result;
    result.reserve(end - begin);
    for (std::size_t i = begin; i < end; ++i) result.push_back(static_cast<int>(i));
    return result;
  }

  void dfs(const std::vector<int>& pool, const std::vector<std::uint32_t>& groups,
           unsigned depth, unsigned cost) {
    if (stop_ != StopReason::None) return;
    if ((nodes_++ & 0x3ff) == 0 && Clock::now() >= deadline_) {
      stop_ = StopReason::Time;
      return;
    }
    const unsigned remaining = kRows - depth;
    if (pool.size() < remaining || improves_bound(cost, remaining, pool, 0)) return;

    for (std::size_t j = 0; j < pool.size(); ++j) {
      if (stop_ != StopReason::None) return;
      if (pool.size() - j < remaining) break;
      if (improves_bound(cost, remaining, pool, j)) break;
      const Candidate& candidate = pool_[pool[j]];
      std::vector<std::uint32_t> halves;
      if (!splits(groups, candidate.signature, &halves)) continue;
      chosen_[depth] = candidate.mask;
      if (remaining == 1) {
        save_best(cost + candidate.weight);
        continue;
      }

      std::vector<int> next;
      next.reserve(pool.size() - j - 1);
      for (std::size_t k = j + 1; k < pool.size(); ++k) {
        const Candidate& next_candidate = pool_[pool[k]];
        // The next candidate may be the final row. Other remaining rows can
        // still have the current weight, so this lower bound is safe even
        // when next_candidate is heavier.
        if (best_ && cost + candidate.weight + next_candidate.weight +
                         candidate.weight * (remaining - 2) >= best_->taps)
          break;
        if (splits(halves, next_candidate.signature, nullptr))
          next.push_back(pool[k]);
      }
      if (next.size() >= remaining - 1)
        dfs(next, halves, depth + 1, cost + candidate.weight);
    }
  }

  void save_best(unsigned taps) {
    if (best_ && taps >= best_->taps) return;
    Best result;
    result.rows = chosen_;
    result.taps = taps;
    std::array<bool, kKeys> seen{};
    for (unsigned i = 0; i < kKeys; ++i) {
      unsigned id = 0;
      for (unsigned row = 0; row < kRows; ++row)
        id |= static_cast<unsigned>(popcount64(keys_[i] & result.rows[row]) & 1U) << row;
      result.ids[i] = id;
      seen[id] = true;
    }
    for (bool value : seen)
      if (!value) return;
    best_ = result;
    improvements_.push_back(taps);
  }

  static std::string hex(Key value) {
    std::ostringstream out;
    out << "0x" << std::hex << std::setw(16) << std::setfill('0') << value;
    return out.str();
  }

  static std::string json_string(const std::string& value) {
    std::ostringstream out;
    out << '"';
    for (const unsigned char c : value) {
      if (c == '"' || c == '\\') out << '\\';
      out << c;
    }
    out << '"';
    return out.str();
  }

  std::string to_json() const {
    std::ostringstream out;
    const auto elapsed = std::chrono::duration<double>(Clock::now() - start_).count();
    out << "{\"status\":" << json_string(status_)
        << ",\"max_cap\":" << options_.max_cap
        << ",\"generated_cap\":" << generated_cap_
        << ",\"proved_cap\":" << proved_cap_
        << ",\"candidates\":" << by_signature_.size()
        << ",\"enumerated_masks\":" << enumerated_
        << ",\"nodes\":" << nodes_
        << ",\"elapsed_seconds\":" << elapsed
        << ",\"proof_scope\":\"independent XOR rows; completed candidate layers only\""
        << ",\"best\":";
    if (!best_) {
      out << "null";
    } else {
      out << "{\"rows\":[";
      for (unsigned row = 0; row < kRows; ++row) {
        if (row) out << ',';
        out << json_string(hex(best_->rows[row]));
      }
      out << "] ,\"row_taps\":[";
      for (unsigned row = 0; row < kRows; ++row) {
        if (row) out << ',';
        out << popcount64(best_->rows[row]);
      }
      out << "] ,\"taps\":" << best_->taps
          << ",\"independent_xors\":" << (best_->taps - kRows)
          << ",\"ids\":[";
      for (unsigned i = 0; i < kKeys; ++i) {
        if (i) out << ',';
        out << best_->ids[i];
      }
      out << "]}";
    }
    out << ",\"stages\":[";
    for (std::size_t i = 0; i < stages_.size(); ++i) {
      if (i) out << ',';
      const auto& stage = stages_[i];
      out << "{\"cap\":" << stage.cap
          << ",\"candidates\":" << stage.candidates
          << ",\"nodes\":" << stage.nodes
          << ",\"complete\":" << (stage.complete ? "true" : "false")
          << ",\"improvements\":[";
      for (std::size_t j = 0; j < stage.improvements.size(); ++j) {
        if (j) out << ',';
        out << stage.improvements[j];
      }
      out << "]}";
    }
    out << "]}";
    return out.str();
  }
};

}  // namespace

int main(int argc, char** argv) {
  try {
    const auto options = parse_options(argc, argv);
    const auto keys = read_keys(options.path);
    Searcher searcher(keys, options);
    std::cout << searcher.run() << '\n';
    return 0;
  } catch (const std::exception& error) {
    std::cerr << "error: " << error.what() << '\n' << usage() << '\n';
    return 2;
  }
}
